airbyte_snowflake:
  outputs:
    dev:
      type: snowflake
      threads: 1
      account: {{snowflake account details}}
      user: AIRBYTE_USER
      password: password
      role: AIRBYTE_ROLE
      warehouse: AIRBYTE_WAREHOUSE
      database: AIRBYTE_DATABASE
      schema: AIRBYTE_SCHEMA
  target: dev

      

      
